### ISSUE TITLE
第 4 点：微信内置浏览器内，一长段文字不能正确折行

### ISSUE THREAD

**Issue by pimgeek** [mindpin/chatflow#4]
Android 4.2.2 版本系统上利用微信 6.0.2 版本内置浏览器查看对话泡泡，文字不能正确折行。但在 同样的系统上，Chrome 39.0 版本则可以正确折行
### 微信 6.0.2 内置浏览器

![](http://img.teamkn.com/i/lFgfMq3t.png)
### Chrome 39.0 浏览器

![](http://img.teamkn.com/i/FTuB4A6Y.png)

**Comment by ben7th** [comment]
- 尝试修改了，目前在我的微信浏览器内效果正确。
