### ISSUE TITLE
第 5 点：微信内置浏览器内，长段文字中的英文单词遇到空格后错误折行

### ISSUE THREAD

**Issue by pimgeek** [mindpin/chatflow#5]
Android 4.2.2 版本系统上利用微信 6.0.2 版本内置浏览器查看对话泡泡，长段文字中的英文单词遇到空格后错误折行。但在 同样的系统上，Chrome 39.0 版本则不会错误折行
### 微信 6.0.2 内置浏览器

![](http://img.teamkn.com/i/lXRSsVxS.png)
### Chrome 39.0 浏览器

![](http://img.teamkn.com/i/VWpSOBp7.png)

**Comment by ben7th** [comment]
由于微信浏览器自身的问题，换行模式只能在以下两种择其一：
1. 英文单词后的中文会换行。也就是现在的模式，在这种模式下，如果不想出现换行，则中英文单词中间不加空格可以规避此问题。
2. 英文单词也参与强制换行，也就是说一个较长的英文单词会在中间折行，如下图：

![](http://img.teamkn.com/i/fDtHOimV.png)

以上两种模式只能择其一。确定后我来修改CSS。

**Comment by pimgeek** [comment]
选择 Break-all 模式。
