### ISSUE TITLE
第 6 点：希望能够对 text 文字增加默认的 margin 值

### ISSUE THREAD

**Issue by pimgeek** [mindpin/chatflow#6]
下图中，红色方框标明了默认间距，绿色方框标明了增加 margin-bottom: 16px 后的间距。
![](http://img.teamkn.com/i/CIqmjVUw.png)

希望同一个“泡泡”中的相邻元素之间，默认间距都能一致地增大到 16px。

**Comment by ben7th** [comment]
- 因为其他场合下的可能需要margin值为零，所以默认值只能是0.（我改成默认值16px的话，其他场景又要求默认值0，我怎么办。顾此失彼。）

需要实现你要的效果，最简单的方法是通过插入空行来解决：

``` yaml
    - text: ''
      delay: 0
```
