### ISSUE TITLE
第 8 点：对话泡泡在 Safari for iPad 2 上无法通过点击进入下一段内容

### ISSUE THREAD

**Issue by pimgeek** [mindpin/chatflow#8]
请在 Safari for iPad 2 上打开 http://pimgeek.github.io/chat/google/ 重现此问题。

**Comment by ben7th** [comment]
- iPad 上的问题已经修改
- Safari 的 PC 版上确定有此问题？目前我发现的问题是和触摸事件有关的，Safari 的 PC 版理论上不应有此问题。
